# Generated by Django 5.0.4 on 2026-06-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('senior_citizen', models.BooleanField(default=False)),
                ('partner', models.BooleanField(default=False)),
                ('dependents', models.BooleanField(default=False)),
                ('tenure', models.IntegerField(help_text='Months as customer')),
                ('phone_service', models.BooleanField(default=True)),
                ('multiple_lines', models.CharField(default='No', max_length=20)),
                ('internet_service', models.CharField(choices=[('DSL', 'DSL'), ('Fiber optic', 'Fiber optic'), ('No', 'No')], max_length=20)),
                ('online_security', models.CharField(default='No', max_length=20)),
                ('online_backup', models.CharField(default='No', max_length=20)),
                ('device_protection', models.CharField(default='No', max_length=20)),
                ('tech_support', models.CharField(default='No', max_length=20)),
                ('streaming_tv', models.CharField(default='No', max_length=20)),
                ('streaming_movies', models.CharField(default='No', max_length=20)),
                ('contract', models.CharField(choices=[('Month-to-month', 'Month-to-month'), ('One year', 'One year'), ('Two year', 'Two year')], max_length=20)),
                ('paperless_billing', models.BooleanField(default=False)),
                ('payment_method', models.CharField(choices=[('Electronic check', 'Electronic check'), ('Mailed check', 'Mailed check'), ('Bank transfer (automatic)', 'Bank transfer (automatic)'), ('Credit card (automatic)', 'Credit card (automatic)')], max_length=40)),
                ('monthly_charges', models.FloatField()),
                ('total_charges', models.FloatField()),
                ('churn', models.BooleanField(default=False)),
                ('churn_risk_score', models.FloatField(blank=True, help_text='0-100 probability', null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
